import samsungImg from './assets/samsung.jpg';
import jblImg from './assets/jbl.jpg';
import masaaiImg from './assets/masaai.jpg';
import jogooImg from './assets/jogoo.jpg';
import budsImg from './assets/buds.jpg';
import kitengeImg from './assets/kitenge.jpg';

export const categories = [
  { id: 'all', label: 'All', materialSymbol: 'shopping_bag' },
  { id: 'electronics', label: 'Electronics', materialSymbol: 'smartphone' },
  { id: 'grocery', label: 'Grocery', materialSymbol: 'grocery' },
  { id: 'fashion', label: 'Fashion', materialSymbol: 'checkroom' },
  { id: 'beauty', label: 'Beauty', materialSymbol: 'spa' },
  { id: 'home', label: 'Home', materialSymbol: 'home' },
  { id: 'sports', label: 'Sports', materialSymbol: 'fitness_center' },
  { id: 'baby', label: 'Baby', materialSymbol: 'child_care' },
  { id: 'health', label: 'Health', materialSymbol: 'local_pharmacy' },
  { id: 'books', label: 'Books', materialSymbol: 'menu_book' },
  { id: 'automotive', label: 'Auto', materialSymbol: 'directions_car' },
];

export const products = [
  {
    id: 1,
    name: 'Samsung Galaxy A15',
    vendor: 'TechZone Nairobi',
    vendorId: 1,
    price: 18500,
    originalPrice: 21000,
    category: 'electronics',
    image: samsungImg,
    rating: 4.5,
    reviews: 128,
    badge: 'Hot Deal',
    description: 'Android 14, dual SIM, 50MP camera. Choose storage and finish.',
    inStock: true,
    variants: [
      { id: '1-128-blk', label: '128GB · Black', price: 18500, originalPrice: 21000, inStock: true },
      { id: '1-128-blu', label: '128GB · Blue', price: 18900, originalPrice: 21400, inStock: true },
      { id: '1-256-blk', label: '256GB · Black', price: 21200, originalPrice: 23800, inStock: true },
      { id: '1-256-blu', label: '256GB · Blue', price: 21800, originalPrice: 24400, inStock: false },
    ],
  },
  {
    id: 2,
    name: 'JBL Flip 6 Speaker',
    vendor: 'SoundHub KE',
    vendorId: 2,
    price: 8900,
    originalPrice: 11000,
    category: 'electronics',
    image: jblImg,
    rating: 4.8,
    reviews: 64,
    badge: 'Top Rated',
    description: 'Waterproof Bluetooth speaker, 12hrs battery. Pick a colour.',
    inStock: true,
    variants: [
      { id: '2-blk', label: 'Black', price: 8900, originalPrice: 11000, inStock: true },
      { id: '2-red', label: 'Red', price: 9200, originalPrice: 11400, inStock: true },
      { id: '2-blu', label: 'Ocean Blue', price: 9100, originalPrice: 11300, inStock: true },
    ],
  },
  {
    id: 3,
    name: 'Maasai Beaded Sandals',
    vendor: 'Heritage Crafts KE',
    vendorId: 3,
    price: 1750,
    originalPrice: null,
    category: 'fashion',
    image: masaaiImg,
    rating: 4.6,
    reviews: 43,
    badge: 'Local Made',
    description: 'Handcrafted leather sole. Select your EU size.',
    inStock: true,
    variants: [
      { id: '3-eu38', label: 'EU 38', price: 1750, originalPrice: null, inStock: true },
      { id: '3-eu40', label: 'EU 40', price: 1800, originalPrice: null, inStock: true },
      { id: '3-eu42', label: 'EU 42', price: 1850, originalPrice: null, inStock: true },
      { id: '3-eu44', label: 'EU 44', price: 1900, originalPrice: null, inStock: false },
    ],
  },
  {
    id: 4,
    name: 'Jogoo Unga 2kg',
    vendor: 'Mama Mboga Supplies',
    vendorId: 4,
    price: 210,
    originalPrice: 240,
    category: 'grocery',
    image: jogooImg,
    rating: 4.3,
    reviews: 312,
    badge: 'Essentials',
    description: 'Premium white maize flour. Singles or multipack.',
    inStock: true,
    variants: [
      { id: '4-1', label: '1 × 2kg pack', price: 210, originalPrice: 240, inStock: true },
      { id: '4-2', label: '2 × 2kg packs', price: 400, originalPrice: 460, inStock: true },
    ],
  },
  {
    id: 5,
    name: 'Wireless Earbuds Pro',
    vendor: 'TechZone Nairobi',
    vendorId: 1,
    price: 2900,
    originalPrice: 3800,
    category: 'electronics',
    image: budsImg,
    rating: 4.1,
    reviews: 87,
    badge: null,
    description: 'True wireless, 24hr battery with case. Colour options.',
    inStock: true,
    variants: [
      { id: '5-blk', label: 'Matte Black', price: 2900, originalPrice: 3800, inStock: true },
      { id: '5-wht', label: 'Pearl White', price: 3050, originalPrice: 3950, inStock: true },
    ],
  },
  {
    id: 6,
    name: 'Kitenge Wrap Dress',
    vendor: 'Kuumba Fashions',
    vendorId: 5,
    price: 2400,
    originalPrice: null,
    category: 'fashion',
    image: kitengeImg,
    rating: 4.7,
    reviews: 56,
    badge: 'Trending',
    description: 'African print wrap dress. Same cut, choose size.',
    inStock: true,
    variants: [
      { id: '6-s', label: 'Size S', price: 2400, originalPrice: null, inStock: true },
      { id: '6-m', label: 'Size M', price: 2400, originalPrice: null, inStock: true },
      { id: '6-l', label: 'Size L', price: 2500, originalPrice: null, inStock: true },
    ],
  },
  {
    id: 7,
    name: 'Yoga Mat 6mm',
    vendor: 'FitLife Kenya',
    vendorId: 6,
    price: 2200,
    originalPrice: 2800,
    category: 'sports',
    image: budsImg,
    rating: 4.4,
    reviews: 31,
    badge: 'Hot Deal',
    description: 'Non-slip TPE mat with carry strap. Colour options.',
    inStock: true,
    variants: [
      { id: '7-teal', label: 'Teal', price: 2200, originalPrice: 2800, inStock: true },
      { id: '7-grey', label: 'Grey', price: 2350, originalPrice: 2950, inStock: true },
    ],
  },
  {
    id: 8,
    name: 'Baby Diapers Pack (Size 3)',
    vendor: 'Little Ones Store',
    vendorId: 7,
    price: 1450,
    originalPrice: null,
    category: 'baby',
    image: jogooImg,
    rating: 4.6,
    reviews: 89,
    badge: 'Essentials',
    description: 'Soft, absorbent diapers. Pack size options.',
    inStock: true,
    variants: [
      { id: '8-48', label: '48 pcs', price: 1450, originalPrice: null, inStock: true },
      { id: '8-72', label: '72 pcs', price: 1990, originalPrice: null, inStock: true },
    ],
  },
  {
    id: 9,
    name: 'Vitamin C 1000mg (60 tabs)',
    vendor: 'Wellness Plus',
    vendorId: 8,
    price: 950,
    originalPrice: 1200,
    category: 'health',
    image: jblImg,
    rating: 4.5,
    reviews: 112,
    badge: 'Top Rated',
    description: 'Immune support supplement. Same strength, bottle size options.',
    inStock: true,
    variants: [
      { id: '9-60', label: '60 tabs', price: 950, originalPrice: 1200, inStock: true },
      { id: '9-120', label: '120 tabs', price: 1650, originalPrice: 2100, inStock: true },
    ],
  },
  {
    id: 10,
    name: 'Swahili for Beginners',
    vendor: 'PageTurner Books',
    vendorId: 9,
    price: 890,
    originalPrice: null,
    category: 'books',
    image: masaaiImg,
    rating: 4.8,
    reviews: 204,
    badge: 'Bestseller',
    description: 'Learn conversational Swahili. Paperback or e-book.',
    inStock: true,
    variants: [
      { id: '10-pb', label: 'Paperback', price: 890, originalPrice: null, inStock: true },
      { id: '10-eb', label: 'E-book', price: 450, originalPrice: null, inStock: true },
    ],
  },
  {
    id: 11,
    name: 'Shea Butter Body Lotion 400ml',
    vendor: 'Glow Beauty',
    vendorId: 10,
    price: 750,
    originalPrice: null,
    category: 'beauty',
    image: kitengeImg,
    rating: 4.3,
    reviews: 67,
    badge: null,
    description: 'Deep moisture for dry skin. Scent options.',
    inStock: true,
    variants: [
      { id: '11-van', label: 'Vanilla', price: 750, originalPrice: null, inStock: true },
      { id: '11-coc', label: 'Coconut', price: 750, originalPrice: null, inStock: true },
    ],
  },
  {
    id: 12,
    name: 'LED Desk Lamp',
    vendor: 'HomeComfort',
    vendorId: 11,
    price: 1890,
    originalPrice: 2400,
    category: 'home',
    image: samsungImg,
    rating: 4.2,
    reviews: 41,
    badge: 'Trending',
    description: 'Adjustable brightness, USB charging port. Colour options.',
    inStock: true,
    variants: [
      { id: '12-wht', label: 'White', price: 1890, originalPrice: 2400, inStock: true },
      { id: '12-blk', label: 'Black', price: 1990, originalPrice: 2500, inStock: true },
    ],
  },
  {
    id: 13,
    name: 'Car Phone Mount (Vent)',
    vendor: 'AutoParts KE',
    vendorId: 12,
    price: 650,
    originalPrice: null,
    category: 'automotive',
    image: budsImg,
    rating: 4.1,
    reviews: 28,
    badge: null,
    description: 'Secure vent clip mount. Fits most phones.',
    inStock: true,
    variants: [],
  },
];

/** Single sellable SKU for cart + checkout (variant or synthetic default). */
export function getDefaultVariant(product) {
  if (product?.variants?.length) {
    return product.variants.find((v) => v.inStock) || product.variants[0];
  }
  return {
    id: 'default',
    label: '',
    price: product.price,
    originalPrice: product.originalPrice ?? null,
    inStock: product.inStock !== false,
  };
}

/** Lowest variant price for “from” labels on grids. */
export function getListingFromPrice(product) {
  if (!product?.variants?.length) return product.price;
  return Math.min(...product.variants.map((v) => v.price));
}

export function productHasMultiplePrices(product) {
  if (!product?.variants?.length) return false;
  const prices = product.variants.map((v) => v.price);
  return new Set(prices).size > 1;
}

export const vendors = [
  {
    id: 1,
    name: 'TechZone Nairobi',
    region: 'Nairobi Metro',
    owner: 'James Kamau',
    phone: '+254712345678',
    email: 'james@techzone.co.ke',
    category: 'Electronics',
    status: 'approved',
    kycLevel: 2,
    joinDate: '2026-02-15',
    products: 14,
    totalOrders: 234,
    totalRevenue: 1840000,
    escrowBalance: 47800,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.6,
  },
  {
    id: 2,
    name: 'SoundHub KE',
    region: 'Nairobi Metro',
    owner: 'Faith Wanjiku',
    phone: '+254723456789',
    email: 'faith@soundhub.ke',
    category: 'Electronics',
    status: 'approved',
    kycLevel: 2,
    joinDate: '2026-03-01',
    products: 8,
    totalOrders: 89,
    totalRevenue: 678000,
    escrowBalance: 17800,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.8,
  },
  {
    id: 3,
    name: 'Heritage Crafts KE',
    region: 'Rift Valley',
    owner: 'Samuel Ole Ntimama',
    phone: '+254734567890',
    email: 'samuel@heritagecrafts.ke',
    category: 'Fashion',
    status: 'pending',
    kycLevel: 1,
    joinDate: '2026-04-01',
    products: 3,
    totalOrders: 0,
    totalRevenue: 0,
    escrowBalance: 0,
    nextPayout: null,
    avatar: null,
    rating: null,
  },
  {
    id: 4,
    name: 'Mama Mboga Supplies',
    region: 'Western',
    owner: 'Grace Atieno',
    phone: '+254745678901',
    email: 'grace@mamamboga.ke',
    category: 'Grocery',
    status: 'approved',
    kycLevel: 3,
    joinDate: '2026-01-10',
    products: 22,
    totalOrders: 1204,
    totalRevenue: 890000,
    escrowBalance: 24500,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.3,
  },
  {
    id: 5,
    name: 'Kuumba Fashions',
    region: 'Coast',
    owner: 'Amina Hassan',
    phone: '+254756789012',
    email: 'amina@kuumba.ke',
    category: 'Fashion',
    status: 'suspended',
    kycLevel: 2,
    joinDate: '2026-02-28',
    products: 18,
    totalOrders: 67,
    totalRevenue: 145000,
    escrowBalance: 0,
    nextPayout: null,
    avatar: null,
    rating: 4.7,
  },
  {
    id: 6,
    name: 'FitLife Kenya',
    region: 'Nairobi Metro',
    owner: 'Kevin Otieno',
    phone: '+254711223344',
    email: 'hello@fitlife.ke',
    category: 'Sports',
    status: 'approved',
    kycLevel: 2,
    joinDate: '2026-01-20',
    products: 6,
    totalOrders: 45,
    totalRevenue: 120000,
    escrowBalance: 3200,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.4,
  },
  {
    id: 7,
    name: 'Little Ones Store',
    region: 'Nairobi Metro',
    owner: 'Wanjiku Muthoni',
    phone: '+254722334455',
    email: 'care@littleones.ke',
    category: 'Baby',
    status: 'approved',
    kycLevel: 2,
    joinDate: '2026-02-01',
    products: 12,
    totalOrders: 210,
    totalRevenue: 340000,
    escrowBalance: 9100,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.6,
  },
  {
    id: 8,
    name: 'Wellness Plus',
    region: 'Nairobi Metro',
    owner: 'Dr. Peter Njoroge',
    phone: '+254733445566',
    email: 'orders@wellnessplus.ke',
    category: 'Health',
    status: 'approved',
    kycLevel: 3,
    joinDate: '2025-11-10',
    products: 24,
    totalOrders: 512,
    totalRevenue: 890000,
    escrowBalance: 22000,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.5,
  },
  {
    id: 9,
    name: 'PageTurner Books',
    region: 'Nairobi Metro',
    owner: 'Lucy Akinyi',
    phone: '+254744556677',
    email: 'shop@pageturner.ke',
    category: 'Books',
    status: 'approved',
    kycLevel: 2,
    joinDate: '2026-03-05',
    products: 80,
    totalOrders: 1203,
    totalRevenue: 560000,
    escrowBalance: 14000,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.8,
  },
  {
    id: 10,
    name: 'Glow Beauty',
    region: 'Coast',
    owner: 'Halima Omar',
    phone: '+254755667788',
    email: 'hello@glowbeauty.ke',
    category: 'Beauty',
    status: 'approved',
    kycLevel: 2,
    joinDate: '2026-01-05',
    products: 35,
    totalOrders: 188,
    totalRevenue: 210000,
    escrowBalance: 5600,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.3,
  },
  {
    id: 11,
    name: 'HomeComfort',
    region: 'Central',
    owner: 'Eric Kimani',
    phone: '+254766778899',
    email: 'sales@homecomfort.ke',
    category: 'Home',
    status: 'approved',
    kycLevel: 2,
    joinDate: '2025-12-12',
    products: 19,
    totalOrders: 96,
    totalRevenue: 178000,
    escrowBalance: 4100,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.2,
  },
  {
    id: 12,
    name: 'AutoParts KE',
    region: 'Nairobi Metro',
    owner: 'Brian Mutua',
    phone: '+254777889900',
    email: 'parts@autoparts.ke',
    category: 'Automotive',
    status: 'approved',
    kycLevel: 2,
    joinDate: '2026-02-18',
    products: 40,
    totalOrders: 74,
    totalRevenue: 95000,
    escrowBalance: 2800,
    nextPayout: '2026-04-05',
    avatar: null,
    rating: 4.1,
  },
];

export const orders = [
  {
    id: 'MSK-001234',
    customerId: '+254798765432',
    customerName: 'C. Mwenda',
    vendorId: 1,
    product: 'Samsung Galaxy A15',
    amount: 18500,
    commission: 925,
    netVendor: 17575,
    status: 'delivered',
    escrowStatus: 'released',
    otpGenerated: '8821',
    otpConfirmed: true,
    date: '2026-04-01',
    payoutDate: '2026-04-01',
    riderId: null,
  },
  {
    id: 'MSK-001235',
    customerId: '+254787654321',
    customerName: 'B. Njeri',
    vendorId: 1,
    product: 'Wireless Earbuds Pro',
    amount: 2900,
    commission: 145,
    netVendor: 2755,
    status: 'dispatched',
    escrowStatus: 'held',
    otpGenerated: '3374',
    otpConfirmed: false,
    date: '2026-04-02',
    payoutDate: null,
    riderId: 'r-seed-1',
  },
  {
    id: 'MSK-001236',
    customerId: '+254776543210',
    customerName: 'A. Omondi',
    vendorId: 1,
    product: 'Samsung Galaxy A15',
    amount: 18500,
    commission: 925,
    netVendor: 17575,
    status: 'confirmed',
    escrowStatus: 'held',
    otpGenerated: '5519',
    otpConfirmed: false,
    date: '2026-04-02',
    payoutDate: null,
    riderId: null,
  },
  {
    id: 'MSK-001210',
    customerId: '+254765432109',
    customerName: 'D. Waweru',
    vendorId: 4,
    product: 'Jogoo Unga 2kg',
    amount: 210,
    commission: 11,
    netVendor: 199,
    status: 'delivered',
    escrowStatus: 'released',
    otpGenerated: '7723',
    otpConfirmed: true,
    date: '2026-03-30',
    payoutDate: '2026-03-30',
    riderId: null,
  },
];

export const disputes = [
  {
    id: 'DSP-001',
    orderId: 'MSK-001190',
    raisedBy: 'vendor',
    vendor: 'TechZone Nairobi',
    customerPhone: '+254798111222',
    product: 'Samsung Galaxy A15',
    amount: 18500,
    status: 'open',
    reason: 'Customer claims item not received but OTP was shared with rider.',
    date: '2026-04-01',
  },
];

export const platformStats = {
  activeVendors: 10,
  ordersToday: 23,
  revenueToday: 187400,
  activeConversations: 12,
  pendingVendors: 1,
  openDisputes: 1,
  totalRevenue: 3553000,
  totalCommission: 177650,
};
